In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
WHR = pd.read_csv('data/world_happiness_report.csv')
WHR.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [29]:
# 국가별로 피벗테이블 작성
Country_g = pd.pivot_table(WHR, index = ('Country name','year'))
Country_g

                   Freedom to make life choices  Generosity  \
Country name year
Afghanistan  2008                         0.718       0.168
             2009                         0.679       0.190
             2010                         0.600       0.121
             2011                         0.496       0.162
             2012                         0.531       0.236
...                                         ...         ...
Zimbabwe     2016                         0.733      -0.095
             2017                         0.753      -0.098
             2018                         0.763      -0.068
             2019                         0.632      -0.064
             2020                         0.643      -0.009

                   Healthy life expectancy at birth  Life Ladder  \
Country name year
Afghanistan  2008                             50.80        3.724
             2009                             51.20        4.402
             2010                             51.60        4.758
             2011                             51.92        3.832
             2012                             52.24        3.783
...                                             ...          ...
Zimbabwe     2016                             54.40        3.735
             2017                             55.00        3.638
             2018                             55.60        3.616
             2019                             56.20        2.694
             2020                             56.80        3.160

                   Log GDP per capita  Negative affect  \
Country name year
Afghanistan  2008               7.370            0.258
             2009               7.540            0.237
             2010               7.647            0.275
             2011               7.620            0.267
             2012               7.705            0.268
...                               ...              ...
Zimbabwe     2016               7.984            0.209
             2017               8.016            0.224
             2018               8.049            0.212
             2019               7.950            0.235
             2020               7.829            0.346

                   Perceptions of corruption  Positive affect  Social support
Country name year
Afghanistan  2008                      0.882            0.518           0.451
             2009                      0.850            0.584           0.552
             2010                      0.707            0.618           0.539
             2011                      0.731            0.611           0.521
             2012                      0.776            0.710           0.521
...                                      ...              ...             ...
Zimbabwe     2016                      0.724            0.738           0.768
             2017                      0.751            0.806           0.754
             2018                      0.844            0.710           0.775
             2019                      0.831            0.716           0.759
             2020                      0.789            0.703           0.717

[1949 rows x 9 columns]

In [91]:
Country_list = WHR['Country name'].unique().tolist()

In [105]:
# 데이터 레코드가 6개 이상인 국가만 추출
sum = 0
preprocess = []
for i in Country_list:
    if len(i) <= 5 :
        pass
    else:
        #Country_g.loc[[i]]
        print(i)
        preprocess.append(i)
        sum += 1
        
print(sum)
print(preprocess)

Afghanistan
Albania
Algeria
Angola
Argentina
Armenia
Australia
Austria
Azerbaijan
Bahrain
Bangladesh
Belarus
Belgium
Belize
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brazil
Bulgaria
Burkina Faso
Burundi
Cambodia
Cameroon
Canada
Central African Republic
Colombia
Comoros
Congo (Brazzaville)
Congo (Kinshasa)
Costa Rica
Croatia
Cyprus
Czech Republic
Denmark
Djibouti
Dominican Republic
Ecuador
El Salvador
Estonia
Ethiopia
Finland
France
Gambia
Georgia
Germany
Greece
Guatemala
Guinea
Guyana
Honduras
Hong Kong S.A.R. of China
Hungary
Iceland
Indonesia
Ireland
Israel
Ivory Coast
Jamaica
Jordan
Kazakhstan
Kosovo
Kuwait
Kyrgyzstan
Latvia
Lebanon
Lesotho
Liberia
Lithuania
Luxembourg
Madagascar
Malawi
Malaysia
Maldives
Mauritania
Mauritius
Mexico
Moldova
Mongolia
Montenegro
Morocco
Mozambique
Myanmar
Namibia
Netherlands
New Zealand
Nicaragua
Nigeria
North Cyprus
North Macedonia
Norway
Pakistan
Palestinian Territories
Panama
Paraguay
Philippines
Poland
Portugal
Romania
Russia
Rwanda
Saudi Arabia
Senegal
Serbia
Sierra Leone
Singapore
Slovakia
Slovenia
Somalia
Somaliland region
South Africa
South Korea
South Sudan
Sri Lanka
Suriname
Swaziland
Sweden
Switzerland
Taiwan Province of China
Tajikistan
Tanzania
Thailand
Trinidad and Tobago
Tunisia
Turkey
Turkmenistan
Uganda
Ukraine
United Arab Emirates
United Kingdom
United States
Uruguay
Uzbekistan
Venezuela
Vietnam
Zambia
Zimbabwe
137
['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Belarus', 'Belgium', 'Belize', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Colombia', 'Comoros', 'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'El Salvador', 'Estonia', 'Ethiopia', 'Finland', 'France', 'Gambia', 'Georgia', 'Germany', 'Greece', 'Guatemala', 'Guinea', 'Guyana', 'Honduras', 'Hong Kong S.A.R. of China', 'Hungary', 'Iceland', 'Indonesia', 'Ireland', 'Israel', 'Ivory Coast', 'Jamaica', 'Jordan', 'Kazakhstan', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Netherlands', 'New Zealand', 'Nicaragua', 'Nigeria', 'North Cyprus', 'North Macedonia', 'Norway', 'Pakistan', 'Palestinian Territories', 'Panama', 'Paraguay', 'Philippines', 'Poland', 'Portugal', 'Romania', 'Russia', 'Rwanda', 'Saudi Arabia', 'Senegal', 'Serbia', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Somalia', 'Somaliland region', 'South Africa', 'South Korea', 'South Sudan', 'Sri Lanka', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Taiwan Province of China', 'Tajikistan', 'Tanzania', 'Thailand', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam', 'Zambia', 'Zimbabwe']

In [34]:
# 각 컬럼별 결측치 확인
Country_g.isnull().sum()

Freedom to make life choices         32
Generosity                           89
Healthy life expectancy at birth     55
Life Ladder                           0
Log GDP per capita                   36
Negative affect                      16
Perceptions of corruption           110
Positive affect                      22
Social support                       13
dtype: int64

In [38]:
Country_g['Log GDP per capita'].isnull()

Country name  year
Afghanistan   2008    False
              2009    False
              2010    False
              2011    False
              2012    False
                      ...
Zimbabwe      2016    False
              2017    False
              2018    False
              2019    False
              2020    False
Name: Log GDP per capita, Length: 1949, dtype: bool

In [6]:
# Log GDP per capita 결측치 처리 => 결측치 전년도 다음년도 평균으로 대체
Country_g['Log GDP per capita'].fillna()

36

In [ ]:
# Social support 결측치 처리 => 결측치 전년도 다음년도 평균으로 대체